steps:
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/izzeddincelik/FlaskCICD.git"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/fiverr-136c2/flaskapp", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/fiverr-136c2/flaskapp"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["run", "deploy", "flaskapp", "--image", "gcr.io/fiverr-136c2/flaskapp","--region", "us-central1"]
  - name: gcr.io/cloud-builders/gcloud
    args: ["auth", "configure-docker"]
  - name: gcr.io/cloud-builders/gcloud
    args: ["container", "images", "list-tags", "gcr.io/fiverr-136c2/flaskapp", "--format=json", "--sort-by=~timestamp"]
    id: list_images
    env:
      - "IMAGE_TAGS=$(echo ${_DEFAULT_APP_DEPLOYMENT_TAGS} | jq -r '.[] | .tags[]')"
  - name: gcr.io/fiverr-136c2/flaskapp
    args: ["-c", "for ((i=0; i<${#IMAGE_TAGS[@]}-2; i++)); do gcloud container images delete gcr.io/fiverr-136c2/flaskapp@${IMAGE_TAGS[i]} -q; done"]
    env:
      - "IMAGE_TAGS=$(echo ${_DEFAULT_APP_DEPLOYMENT_TAGS} | jq -r '.[] | .tags[]')"
    waitFor: ["list_images"]
