steps:
  - name: "gcr.io/cloud-builders/git"
    args: ["clone", "https://github.com/izzeddincelik/FlaskCICD.git"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/fiverr-136c2/flaskapp", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/fiverr-136c2/flaskapp"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["run", "deploy", "flaskapp", "--image", "gcr.io/fiverr-136c2/flaskapp","--region", "us-central1"]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'images', 'list-tags', 'gcr.io/fiverr-136c2/flaskapp', '--sort-by=TIMESTAMP', '--limit=3', '--format=\'value(digest)\'']
    id: list_images
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'images', 'delete', '$(echo $(cat /builder/home/image_digests.txt) | tr " " "\n")', '-q']
    env:
      - 'DIGESTS=$(cat /builder/home/${ID}.txt)'
    id: delete_images
    waitFor: ['list_images']
